---
- name: instalatar paquete nginx
  yum:
    name: "nginx"
    state: present
- name: configuracion base nginx
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: reload nginx
- name: configuracion vhost nginx
  copy:
    src: files/vhost_default.conf
    dest: /etc/nginx/conf.d/vhost_default.conf
  notify: reload nginx
- name: arrancar nginx
  service:
    name: nginx
    state: started
    enabled: yes          
