---
- name: configurar nginx
  hosts: www
  become: True
  tasks:
    - name: instalar paquete nginx
      yum:
        name: "nginx"
        state: present               
    - name: configuracion base nginx
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
    - name: configuracion vhost nginx
      copy:
        src: files/vhost_default.conf
        dest: /etc/nginx/conf.d/vhost_default.conf
      notify: reload nginx  
    - name: arrancar nginx
      service:
        name: nginx
        state: started
        enabled: yes
  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
- name: desplegar pagina de bienvenida
  hosts: www
  become: True
  tasks:
    - name: copar página de bienvenida
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
